cleanup after testing

diff --git a/.github/workflows/ecs-deploy.yml b/.github/workflows/ecs-deploy.yml
--- a/.github/workflows/ecs-deploy.yml
+++ b/.github/workflows/ecs-deploy.yml
@@ -1,4 +1,4 @@
-name: 'DPC - QuickSight Report Deploy'
+name: 'DPC - ECS Deploy'
 
 on:
   workflow_dispatch:
@@ -13,6 +13,43 @@ on:
         required: true
         type: 'string'
         default: ''
+      ecr_image_tag:
+        description: Image tag to deploy
+        required: false
+        type: 'string'
+        default: 'latest'
+      app-version:
+        description: 'The version of dpc-app being deployed (ex: r###, xx_test_branch).  This will appear in logs under the "version" property".'
+        required: false
+        type: 'string'
+        default: 'unknown'
+      ops-ref:
+        description: Branch of dpc-ops to use
+        required: false
+        type: 'string'
+        default: 'main'
+  workflow_call:
+    inputs:
+      env:
+        description: AWS environment to deploy to
+        required: true
+        type: 'string'
+        default: 'dev'
+      confirm_env:
+        description: Double check for environment
+        required: true
+        type: 'string'
+        default: ''
+      ecr_image_tag:
+        description: Image tag to deploy
+        required: false
+        type: 'string'
+        default: 'latest'
+      app-version:
+        description: 'The version of dpc-app being deployed (ex: r###, xx_test_branch).  This will appear in logs under the "version" property".'
+        required: false
+        type: 'string'
+        default: 'unknown'
       ops-ref:
         description: Branch of dpc-ops to use
         required: false
@@ -20,7 +57,7 @@ on:
         default: 'main'
 
 concurrency:
-  group: deploy-quicksight-report-to-${{ inputs.env }}
+  group: deploy-to-${{ inputs.env }}
   cancel-in-progress: false
 
 permissions:
@@ -37,12 +74,9 @@ jobs:
       contents: read
       id-token: write
     runs-on: codebuild-dpc-app-${{github.run_id}}-${{github.run_attempt}}
+    outputs:
+      image_tag: ${{ steps.image-tag.outputs.image_tag }}
     steps:
-      - name: Fail if not test or prod
-        if: ${{ inputs.env == 'dev' || inputs.env == 'sandbox' }}
-        run: |
-          echo "Only run on test or prod"
-          exit 1
       - name: Run and Fail if Inputs Invalid
         if: ${{ inputs.env != inputs.confirm_env }}
         run: |
@@ -50,18 +84,56 @@ jobs:
           exit 1
 
       - name: AWS Credentials (non-prod)
-        if: ${{ inputs.env == 'test' }}
+        if: ${{ inputs.env == 'dev' || inputs.env == 'test' }}
         uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
         with:
           aws-region: ${{ vars.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
       - name: AWS Credentials (prod)
-        if: ${{ inputs.env == 'prod' }}
+        if: ${{ inputs.env == 'sandbox' || inputs.env == 'prod' }}
         uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
         with:
           aws-region: ${{ vars.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
 
+      - name: Fail if non-release image tag used for upper environments
+        if: ${{ (inputs.env == 'sandbox' || inputs.env == 'prod') && !startsWith(inputs.ecr_image_tag, 'rls-r') }}
+        run: |
+          echo "Release tag must be explicitly specified with format 'rls-rXYZ' for upper environments."
+          exit 1
+
+      - name: Set Deployed Image Tag
+        id: image-tag
+        env:
+          EXPLICIT_TAG: ${{ inputs.ecr_image_tag }}
+        run: |
+          if [ -z $EXPLICIT_TAG ] || [ $EXPLICIT_TAG = 'latest' ]; then
+            image_tag=`aws --region us-east-1 ecr describe-images --repository-name dpc-api --image-ids 'imageTag=latest' '--query=imageDetails[].imageTags[] | [?contains(@, \`rls-\`)] | [0]' --output text`
+            echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
+          else
+          # Note: this will fail if the image doesn't exist
+            aws --region us-east-1 ecr describe-images --repository-name dpc-api --image-ids 'imageTag=${{ inputs.ecr_image_tag }}' > /dev/null
+            echo "image_tag=$EXPLICIT_TAG" >> "$GITHUB_OUTPUT"
+          fi
+          echo $image_tag
+
+      - uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
+        name: Slack Starting
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          # Sends to dpc-deploys
+          payload: |
+            channel: "CMC1E4AEQ"
+            text:  "GHA Deployment to `${{ inputs.env }}` has started"
+            attachments:
+              - color: warning
+                footer: "<${{ github.server_url}}/${{ github.repository}}/actions/runs/${{ github.run_id }}|ECS Deploy - Build ${{ github.run_id }}>"
+                mrkdown_in:
+                  - footer
+                fields:
+                  - title: Image Tag
+                    value: ${{ steps.image-tag.outputs.image_tag }}
       - name: "Checkout code"
         uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
         with:
@@ -75,12 +147,163 @@ jobs:
       - name: Install Tofu
         uses: cmsgov/cdap/actions/setup-tenv@8343fb96563ce4b74c4dececee9b268f42bd4a40
 
-      - name: Verify plan
+      - name: Verify persistent plan
         run: |
-          cd dpc-ops/terraform/lambda/quicksight-reports
-          tofu init -backend-config=backends/${{ inputs.env }}.config
-          tofu plan -var env=${{ inputs.env }} -out dpc-quicksight-report-release-${{ inputs.env }}.tfplan 2>&1
-      - name: Apply plan
+          cd dpc-ops/terraform/${{ inputs.env }}/persistent
+          tofu init
+          tofu plan -out dpc-release-${{ inputs.env }}.tfplan 2>&1
+      - name: Apply persistent plan
         run: |
-          cd dpc-ops/terraform/lambda/quicksight-reports
-          tofu apply dpc-quicksight-report-release-${{ inputs.env }}.tfplan
+          cd dpc-ops/terraform/${{ inputs.env }}/persistent
+          tofu apply dpc-release-${{ inputs.env }}.tfplan
+      - name: Verify main environment plan
+        run: |
+          cd dpc-ops/terraform/${{ inputs.env }}
+          tofu init
+          tofu plan -var 'release_version=${{ inputs.app-version}}' \
+                         -var 'image_tag=${{ steps.image-tag.outputs.image_tag }}' \
+                         -out dpc-release-${{ inputs.env }}.tfplan
+      - name: Apply main environment plan
+        run: |
+          cd dpc-ops/terraform/${{ inputs.env }}
+          tofu apply dpc-release-${{ inputs.env }}.tfplan
+      - uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
+        name: Slack failure
+        if: ${{ failure() }}
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          # Sends to dpc-deploys
+          payload: |
+            channel: "CMC1E4AEQ"
+            text:  "GHA Deployment to `${{ inputs.env }}` has failed in Deploy Job"
+            attachments:
+              - color: danger
+                footer: "<${{ github.server_url}}/${{ github.repository}}/actions/runs/${{ github.run_id }}|ECS Deploy - Build ${{ github.run_id }}>"
+                mrkdown_in:
+                  - footer
+                fields:
+                  - title: Image Tag
+                    value: ${{ needs.deploy.outputs.image_tag }}
+
+  services-up:
+    name: All Services Healthy
+    needs: deploy
+    uses: ./.github/workflows/check_healthy.yml
+    with:
+      env: ${{ inputs.env }}
+    secrets: inherit
+
+  notify-new-relic:
+    name: Notify New Relic
+    permissions:
+      contents: read
+      id-token: write
+    runs-on: codebuild-dpc-app-${{github.run_id}}-${{github.run_attempt}}
+    needs: deploy
+    steps:
+      - name: AWS Credentials (non-prod)
+        if: ${{ inputs.env == 'dev' || inputs.env == 'test' }}
+        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
+        with:
+          aws-region: ${{ vars.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.NON_PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
+      - name: AWS Credentials (prod)
+        if: ${{ inputs.env == 'sandbox' || inputs.env == 'prod' }}
+        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
+        with:
+          aws-region: ${{ vars.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ secrets.PROD_ACCOUNT_ID }}:role/delegatedadmin/developer/dpc-${{ inputs.env }}-github-actions
+      - name: Set env vars from AWS params
+        uses: cmsgov/cdap/actions/aws-params-env-action@main
+        env:
+          AWS_REGION: ${{ vars.AWS_REGION }}
+        with:
+          params: |
+            NEW_RELIC_API_KEY=/dpc/${{ inputs.env }}/newrelic/new_relic_user_key
+      - name: 'Notify New Relic'
+        id: notify-new-relic
+        run: |
+          counter=0
+          for service in dpc-api-${{ inputs.env }} dpc-attribution-${{ inputs.env }} dpc-aggregation-${{ inputs.env }}  dpc-web-${{ inputs.env }} dpc-web-admin-${{ inputs.env }} dpc-web-portal-${{ inputs.env }}
+          do
+            application_stanza=`docker run --rm -e NEW_RELIC_API_KEY="$NEW_RELIC_API_KEY" -e NEW_RELIC_REGION="US" newrelic/cli:v0.18 apm application search --name $service`
+            if [ -z "$application_stanza" ] || [ "$application_stanza" = "null" ]; then
+              echo "Service $service not found in New Relic, skipping gracefully."
+            else
+              application_id=`echo $application_stanza | jq -r ".[] | select(.name == \"$service\") | .applicationId"`
+              if [ -z "$application_id" ] || [ "$application_id" = "null" ]; then
+                 echo "Service $service not found in New Relic, skipping gracefully."
+              else
+                echo "Notifying New Relic about deployment of $service to ${{ inputs.env }}"
+                docker run --rm -e NEW_RELIC_API_KEY="$NEW_RELIC_API_KEY" -e NEW_RELIC_REGION="US" newrelic/cli:v0.18 apm deployment create --applicationId "$application_id" --revision "${{ needs.deploy.outputs.image_tag }}" --user jenkins
+                counter=$((counter+1))
+              fi
+            fi
+          done
+          echo "counter=$counter" >> "$GITHUB_OUTPUT"
+      - name: Slack if nothing to New Relic
+        if: ${{ failure() || steps.notify-new-relic.outputs.counter == 0 }}
+        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          # Sends to dpc-alerts
+          payload: |
+            channel: "CUY7H43DY"
+            text:  "GHA Notification to New Relic of deployment to `${{ inputs.env }}` has failed"
+            attachments:
+              - color: danger
+                text: Although the deployment succeeded, we were unable to notify New Relic
+                footer: "<${{ github.server_url}}/${{ github.repository}}/actions/runs/${{ github.run_id }}|ECS Deploy - Build ${{ github.run_id }}>"
+                mrkdown_in:
+                  - footer
+
+  notify-slack:
+    name: Notify Slack
+    # Force this to run unless the workflow was canceled
+    if: ${{ !cancelled() }}
+    needs:
+      - deploy
+      - services-up
+    permissions:
+      contents: read
+      id-token: write
+    runs-on: codebuild-dpc-app-${{github.run_id}}-${{github.run_attempt}}
+    steps:
+      - uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
+        name: Slack Success
+        if: ${{ needs.services-up.result == 'success' }}
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          # Sends to dpc-deploys
+          payload: |
+            channel: "CMC1E4AEQ"
+            text:  "GHA Deployment to `${{ inputs.env }}` has succeeded"
+            attachments:
+              - color: good
+                footer: "<${{ github.server_url}}/${{ github.repository}}/actions/runs/${{ github.run_id }}|ECS Deploy - Build ${{ github.run_id }}>"
+                mrkdown_in:
+                  - footer
+                fields:
+                  - title: Image Tag
+                    value: ${{ needs.deploy.outputs.image_tag }}
+      - uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
+        name: Slack failure
+        if: ${{ needs.services-up.result != 'success' }}
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          # Sends to dpc-deploys
+          payload: |
+            channel: "CMC1E4AEQ"
+            text:  "GHA Deployment to `${{ inputs.env }}` has failed"
+            attachments:
+              - color: danger
+                footer: "<${{ github.server_url}}/${{ github.repository}}/actions/runs/${{ github.run_id }}|ECS Deploy - Build ${{ github.run_id }}>"
+                mrkdown_in:
+                  - footer
+                fields:
+                  - title: Image Tag
+                    value: ${{ needs.deploy.outputs.image_tag }}
