Slack starting and services-up failing

diff --git a/.github/workflows/ecs-deploy.yml b/.github/workflows/ecs-deploy.yml
--- a/.github/workflows/ecs-deploy.yml
+++ b/.github/workflows/ecs-deploy.yml
@@ -90,8 +90,7 @@ jobs:
         run: |
           maintenance=`aws ecs list-tags-for-resource --resource-arn arn:aws:ecs:us-east-1:755619740999:cluster/dpc-${{ inputs.env }}-backend '--query=tags[?key==\`Maintenance\`].value' --output text`
           echo "maintenance=$maintenance" >> "$GITHUB_OUTPUT"
-          exit 1
-      - name: "Checkout code"
+       - name: "Checkout code"
         if: ${{ inputs.terraform }}
         uses: actions/checkout@v4
         with:
@@ -134,7 +133,8 @@ jobs:
     steps:
       - name: Fake services up
         run: |
-          echo "Pretend worked"
+          echo "Pretend failed"
+          exit 1
   services-up-hold:
     name: All Services Healthy
     if: ${{ false }}
