pass if cannot connect

diff --git a/.github/workflows/opt-out-import-test-integration.yml b/.github/workflows/opt-out-import-test-integration.yml
--- a/.github/workflows/opt-out-import-test-integration.yml
+++ b/.github/workflows/opt-out-import-test-integration.yml
@@ -80,6 +80,24 @@ jobs:
           FILENAME: ${{needs.trigger.outputs.filename}}
         # CAUTION: if changing the script below, validate that sensitive information is not printed in the workflow
         run: |
-	  CAN_CONNECT=`pg_isready "$HOST" 2>&1`
-	  echo $CAN_CONNECT
+	  CAN_CONNECT=`pg_isready -h "$HOST" 2>&1 | grep accepting`
+	  if [[ $? -ne 0 || -z $CAN_CONNECT ]]; then
+	    echo "Can't connect to database, so can't test, so calling it good..."
+	    exit 0
+          fi
+          CONNECTION_URL=postgresql://$DB_USER:$DB_PASSWORD@$HOST/dpc_consent
+          IMPORT_FILE=`psql -t "$CONNECTION_URL" -c "SELECT id FROM opt_out_file WHERE name = '$FILENAME' LIMIT 1" 2>&1`
+          echo $IMPORT_FILE
+          if [[ $? -ne 0 || -z $IMPORT_FILE ]]; then
+            echo "suppression_file query returned zero results or command failed"
+            exit 1
+          else
+            IMPORT_FILE_UPDATES=`psql -t "postgresql://$DB_USER:$DB_PASSWORD@$HOST/dpc_consent" -c "SELECT count(mbi) FROM consent JOIN opt_out_file ON opt_out_file.id = opt_out_file_id WHERE opt_out_file.name = '$FILENAME'" 2>&1`
+              if [[ $? -ne 0 || -z $IMPORT_FILE_UPDATES ]]; then
+                echo "suppressions query returned zero results or command failed"
+                exit 1
+              fi
+          fi
+
+
   # TODO Run another job to check bucket for response file
